name: CI Pipeline
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-with: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: echo "Instalando dependencias..."
      - name: Lint
        run: echo "Ejecutando Linter..."
      - name: Test
        run: echo "Ejecutando Pruebas..."
